export type Severity = "Low" | "Moderate" | "High" | "Critical";

export type ObdCode = {
  code: string;
  title: string;
  system: string;
  severity: Severity;
  summary: string;
  symptoms: string[];
  possibleCauses: string[];
  recommendedChecks: string[];
  drivingAdvice: string;
  questionsForShop: string[];
  generic: boolean;
};

const q = [
  "What testing confirmed the failed component?",
  "Were wiring, connectors, and related systems checked before recommending parts?",
];

const c = (
  code: string, title: string, system: string, severity: Severity, summary: string,
  symptoms: string[], causes: string[], checks: string[], drivingAdvice: string,
  questionsForShop: string[] = q
): ObdCode => ({
  code, title, system, severity, summary, symptoms,
  possibleCauses: causes, recommendedChecks: checks, drivingAdvice,
  questionsForShop, generic: code[1] === "0"
});

export const obdCodes: ObdCode[] = [
  c("P0100","Mass or Volume Air Flow Circuit Malfunction","Air intake and fuel control","Moderate","The engine computer detected a problem in the mass-air-flow sensor circuit.",["Check Engine Light","Poor acceleration","Rough idle","Reduced fuel economy"],["Dirty or faulty MAF sensor","Intake air leak","Damaged wiring or connector","Restricted air filter"],["Inspect the air filter and intake tube","Check the MAF connector and wiring","Compare MAF readings with expected airflow","Check for unmetered air leaks"],"Usually driveable briefly if it runs normally, but diagnose soon."),
  c("P0101","Mass or Volume Air Flow Circuit Range/Performance","Air intake and fuel control","Moderate","Measured airflow does not match what the computer expects.",["Hesitation","Rough idle","Poor fuel economy","Reduced power"],["Contaminated MAF sensor","Vacuum or intake leak","Restricted intake","Incorrect sensor readings"],["Inspect the intake system","Check for vacuum leaks","Review live MAF data"],"Drive cautiously and schedule diagnosis soon."),
  c("P0128","Coolant Thermostat Below Regulating Temperature","Cooling system","Moderate","The engine is taking too long to reach its expected operating temperature.",["Low heater output","Reduced fuel economy","Temperature gauge stays low"],["Thermostat stuck open","Low coolant","Coolant-temperature sensor issue","Cooling fan running too often"],["Check coolant level when cold","Compare coolant temperature with ambient temperature","Observe warm-up rate","Inspect thermostat operation"],"Usually driveable if it is not overheating and coolant level is correct."),
  c("P0130","Oxygen Sensor Circuit Malfunction (Bank 1, Sensor 1)","Fuel and emissions control","Moderate","The computer detected a fault involving the upstream oxygen sensor on Bank 1.",["Check Engine Light","Reduced fuel economy","Possible rough running"],["Aging oxygen sensor","Wiring damage","Exhaust leak","Fuel-mixture problem"],["Inspect wiring and connector","Check for exhaust leaks","Review live oxygen-sensor data","Confirm fuel trims before replacing the sensor"],"Usually driveable if the engine runs normally.",["Was the sensor tested with live data?","Were exhaust leaks and fuel-mixture problems ruled out?"]),
  c("P0135","Oxygen Sensor Heater Circuit Malfunction (Bank 1, Sensor 1)","Fuel and emissions control","Moderate","The heater circuit for the upstream Bank 1 oxygen sensor is not operating as expected.",["Check Engine Light","Longer warm-up to closed loop","Possible reduced fuel economy"],["Failed heater element","Fuse issue","Wiring or connector damage","Control-circuit fault"],["Check related fuses","Inspect wiring","Test heater resistance and power supply"],"Usually driveable, but repair soon."),
  c("P0171","System Too Lean (Bank 1)","Fuel and air metering","Moderate","Bank 1 is receiving too much air, too little fuel, or incorrect sensor information.",["Rough idle","Hesitation","Poor acceleration","Possible misfire"],["Vacuum leak","Dirty MAF sensor","Low fuel pressure","Exhaust leak","Injector problem"],["Check fuel trims at idle and higher RPM","Smoke-test the intake","Inspect MAF data","Test fuel pressure"],"Stop if the engine misfires badly or the light flashes."),
  c("P0172","System Too Rich (Bank 1)","Fuel and air metering","Moderate","Bank 1 is receiving too much fuel, too little air, or incorrect sensor information.",["Fuel smell","Black exhaust smoke","Poor fuel economy","Rough idle"],["Leaking injector","High fuel pressure","Faulty MAF sensor","Restricted intake","Incorrect coolant-temperature reading"],["Review fuel trims","Inspect air intake","Check injector leakage","Test fuel pressure"],"Limit driving if there is heavy smoke, fuel odor, or poor running."),
  c("P0174","System Too Lean (Bank 2)","Fuel and air metering","Moderate","Bank 2 is receiving too much air, too little fuel, or incorrect sensor information.",["Rough idle","Hesitation","Poor acceleration","Possible misfire"],["Vacuum leak","Dirty MAF sensor","Low fuel pressure","Exhaust leak","Injector problem"],["Compare both banks' fuel trims","Smoke-test the intake","Inspect MAF data","Test fuel pressure"],"Stop if the engine misfires badly or the light flashes."),
  c("P0175","System Too Rich (Bank 2)","Fuel and air metering","Moderate","Bank 2 is receiving too much fuel, too little air, or incorrect sensor information.",["Fuel smell","Black exhaust smoke","Poor fuel economy","Rough idle"],["Leaking injector","High fuel pressure","Faulty MAF sensor","Restricted intake"],["Compare both banks' fuel trims","Check injector leakage","Test fuel pressure"],"Limit driving if there is heavy smoke, fuel odor, or poor running."),
  c("P0201","Injector Circuit Malfunction – Cylinder 1","Fuel injection","High","The computer detected an electrical problem in the injector circuit for cylinder 1.",["Rough running","Misfire","Reduced power"],["Faulty injector","Open or shorted wiring","Loose connector","Control-module driver fault"],["Inspect injector connector and wiring","Check injector resistance","Verify injector control signal"],"Avoid extended driving with an active misfire."),
  c("P0202","Injector Circuit Malfunction – Cylinder 2","Fuel injection","High","The computer detected an electrical problem in the injector circuit for cylinder 2.",["Rough running","Misfire","Reduced power"],["Faulty injector","Open or shorted wiring","Loose connector","Control-module driver fault"],["Inspect injector connector and wiring","Check injector resistance","Verify injector control signal"],"Avoid extended driving with an active misfire."),
  c("P0300","Random/Multiple Cylinder Misfire Detected","Ignition and combustion","High","The computer detected repeated misfires in one or more cylinders.",["Engine shaking","Rough idle","Loss of power","Flashing or steady Check Engine Light"],["Worn spark plugs","Faulty ignition coils","Injector problem","Vacuum leak","Low compression","Fuel-pressure problem"],["Check freeze-frame data","Inspect plugs and coils","Check injector operation","Test compression if needed"],"Stop driving if the Check Engine Light is flashing or the engine is shaking severely.",["Which cylinders are misfiring?","What test proved the recommended part failed?","Was compression checked if ignition and fuel tests passed?"]),
  c("P0301","Cylinder 1 Misfire Detected","Ignition and combustion","High","The computer detected repeated misfires in cylinder 1.",["Engine shaking","Rough idle","Loss of power","Flashing or steady Check Engine Light"],["Worn spark plug","Faulty ignition coil","Injector problem","Vacuum leak","Low compression"],["Inspect the plug and coil","Swap-test the coil where appropriate","Check injector operation","Test compression if needed"],"Stop driving if the light flashes or the engine shakes severely."),
  c("P0302","Cylinder 2 Misfire Detected","Ignition and combustion","High","The computer detected repeated misfires in cylinder 2.",["Engine shaking","Rough idle","Loss of power","Flashing or steady Check Engine Light"],["Worn spark plug","Faulty ignition coil","Injector problem","Vacuum leak","Low compression"],["Inspect the plug and coil","Swap-test the coil where appropriate","Check injector operation","Test compression if needed"],"Stop driving if the light flashes or the engine shakes severely."),
  c("P0303","Cylinder 3 Misfire Detected","Ignition and combustion","High","The computer detected repeated misfires in cylinder 3.",["Engine shaking","Rough idle","Loss of power","Flashing or steady Check Engine Light"],["Worn spark plug","Faulty ignition coil","Injector problem","Vacuum leak","Low compression"],["Inspect the plug and coil","Swap-test the coil where appropriate","Check injector operation","Test compression if needed"],"Stop driving if the light flashes or the engine shakes severely."),
  c("P0304","Cylinder 4 Misfire Detected","Ignition and combustion","High","The computer detected repeated misfires in cylinder 4.",["Engine shaking","Rough idle","Loss of power","Flashing or steady Check Engine Light"],["Worn spark plug","Faulty ignition coil","Injector problem","Vacuum leak","Low compression"],["Inspect the plug and coil","Swap-test the coil where appropriate","Check injector operation","Test compression if needed"],"Stop driving if the light flashes or the engine shakes severely."),
  c("P0325","Knock Sensor 1 Circuit Malfunction","Engine sensors","Moderate","The computer detected a fault in the knock-sensor circuit.",["Check Engine Light","Reduced performance","Possible spark knock"],["Faulty knock sensor","Wiring damage","Connector corrosion","Incorrect installation"],["Inspect wiring","Check sensor mounting","Test circuit and signal"],"Usually driveable cautiously, but prolonged knock can damage an engine."),
  c("P0335","Crankshaft Position Sensor A Circuit Malfunction","Engine timing sensors","High","The crankshaft-position signal is missing or unreliable.",["No-start","Stalling","Tachometer drop","Intermittent shutdown"],["Failed crank sensor","Damaged wiring","Reluctor-wheel issue","Timing problem"],["Check RPM data while cranking","Inspect wiring","Test power, ground, and signal"],"The vehicle may stall or fail to start; avoid relying on it for normal driving."),
  c("P0340","Camshaft Position Sensor A Circuit Malfunction","Engine timing sensors","High","The camshaft-position signal is missing, implausible, or electrically faulty.",["Hard starting","Stalling","Reduced power","Extended cranking"],["Failed cam sensor","Wiring fault","Timing-chain or belt problem","Reluctor issue"],["Inspect connector and wiring","Compare cam and crank signals","Check mechanical timing if needed"],"Drive only as needed for diagnosis; stalling or no-start may occur."),
  c("P0401","Exhaust Gas Recirculation Flow Insufficient","Emissions control","Moderate","The computer commanded EGR flow but measured less than expected.",["Check Engine Light","Possible pinging","Possible roughness"],["Carbon-blocked passages","Stuck EGR valve","Faulty pressure sensor","Vacuum or wiring issue"],["Command the EGR valve with a scan tool","Inspect passages for carbon","Test related sensors"],"Usually driveable, but repair to restore emissions control."),
  c("P0402","Exhaust Gas Recirculation Flow Excessive","Emissions control","Moderate","More EGR flow is occurring than expected.",["Rough idle","Stalling","Hesitation"],["EGR valve stuck open","Control solenoid fault","Incorrect sensor reading"],["Inspect EGR valve seating","Command valve operation","Check vacuum or wiring"],"Drive cautiously because stalling may occur."),
  c("P0420","Catalyst System Efficiency Below Threshold (Bank 1)","Emissions control","Moderate","The computer believes the Bank 1 catalytic converter is not reducing emissions efficiently enough.",["Check Engine Light","Possible sulfur smell","Possible reduced power","Often no noticeable symptom"],["Aging catalytic converter","Exhaust leak","Oxygen-sensor issue","Unresolved misfire or rich-running condition"],["Check for exhaust leaks","Review oxygen-sensor data","Confirm there are no active misfires or fuel-control problems","Test converter efficiency"],"Usually driveable if there is no flashing light, overheating converter, or major power loss.",["Were exhaust leaks ruled out?","Were misfires and fuel-trim problems corrected first?","What test confirmed the converter itself is inefficient?"]),
  c("P0430","Catalyst System Efficiency Below Threshold (Bank 2)","Emissions control","Moderate","The computer believes the Bank 2 catalytic converter is not reducing emissions efficiently enough.",["Check Engine Light","Possible sulfur smell","Possible reduced power","Often no noticeable symptom"],["Aging catalytic converter","Exhaust leak","Oxygen-sensor issue","Unresolved misfire or rich-running condition"],["Check for exhaust leaks","Review oxygen-sensor data","Confirm there are no active misfires or fuel-control problems"],"Usually driveable if there is no flashing light, overheating converter, or major power loss."),
  c("P0440","Evaporative Emission Control System Malfunction","Evaporative emissions","Low","The EVAP system detected a general fault.",["Check Engine Light","Possible fuel odor","Usually no drivability symptoms"],["Loose or damaged fuel cap","Cracked EVAP hose","Stuck purge valve","Faulty vent valve","Damaged canister"],["Inspect and tighten the fuel cap","Check hoses and connectors","Perform an EVAP smoke test","Command purge and vent valves"],"Usually safe to drive if there is no strong fuel smell."),
  c("P0442","Evaporative Emission Control System Leak Detected – Small Leak","Evaporative emissions","Low","The EVAP system detected a small vapor leak.",["Check Engine Light","Usually no drivability symptoms"],["Loose fuel cap","Small cracked hose","Leaking purge or vent valve","Canister leak"],["Inspect the cap seal","Check hoses","Perform a smoke test"],"Usually safe to drive if there is no fuel smell."),
  c("P0446","Evaporative Emission Control System Vent Control Circuit","Evaporative emissions","Low","The EVAP vent-control circuit is not operating as expected.",["Check Engine Light","Usually no drivability symptoms"],["Faulty vent valve","Wiring or connector fault","Blocked vent filter","Canister issue"],["Inspect wiring and connector","Command the vent valve","Check vent airflow and filter"],"Usually safe to drive if there is no fuel smell."),
  c("P0455","Evaporative Emission Control System Leak Detected – Large Leak","Evaporative emissions","Low","The EVAP system detected a large leak or could not seal.",["Check Engine Light","Possible fuel odor"],["Loose or missing fuel cap","Disconnected hose","Stuck vent valve","Large system leak"],["Check the fuel cap","Inspect hoses","Perform a smoke test","Test purge and vent valves"],"Usually safe to drive if there is no strong fuel smell."),
  c("P0456","Evaporative Emission Control System Leak Detected – Very Small Leak","Evaporative emissions","Low","The EVAP system detected a very small vapor leak.",["Check Engine Light","Usually no drivability symptoms"],["Cap-seal leak","Tiny hose crack","Slight valve leakage"],["Inspect the cap seal","Perform a low-pressure smoke test","Test purge and vent sealing"],"Usually safe to drive if there is no fuel smell."),
  c("P0457","Evaporative Emission Control System Leak Detected – Fuel Cap Loose/Off","Evaporative emissions","Low","The EVAP system detected a leak consistent with a loose or missing fuel cap.",["Check Engine Light","Possible fuel odor"],["Loose cap","Missing cap","Damaged cap seal","Filler-neck issue"],["Tighten and inspect the cap","Inspect the filler neck","Clear the code only after the system is sealed"],"Usually safe to drive if there is no strong fuel smell."),
  c("P0499","Evaporative Emission System Vent Valve Control Circuit High","Evaporative emissions","Low","The EVAP vent-valve control circuit voltage is higher than expected.",["Check Engine Light","Usually no drivability symptoms"],["Open control circuit","Faulty vent valve","Connector corrosion","Wiring damage","Control-module fault"],["Inspect the vent-valve connector and harness","Check power and control circuits","Command the valve with a scan tool","Confirm the valve is not frozen or contaminated"],"Usually driveable if there is no fuel smell; diagnose before emissions testing."),
  c("P0500","Vehicle Speed Sensor Malfunction","Vehicle speed input","High","The computer is not receiving a reliable vehicle-speed signal.",["Speedometer may fail","Transmission shifting problems","ABS or traction lights","Cruise control may stop working"],["Faulty speed sensor","Wiring damage","Wheel-speed sensor issue","Tone-ring damage"],["Check related modules for codes","Inspect live speed data","Inspect wiring and tone rings"],"Use caution because shifting, ABS, and speed display may be affected."),
  c("P0562","System Voltage Low","Charging and electrical system","High","System voltage dropped below the expected operating range.",["Battery light","Slow cranking","Warning lights","Stalling"],["Weak battery","Alternator problem","Loose or corroded connections","Drive-belt issue"],["Measure battery voltage engine-off and running","Load-test the battery","Inspect terminals, grounds, belt, and charging output"],"Do not continue far if the battery light is on or voltage is dropping."),
  c("P0606","Powertrain Control Module Processor Fault","Engine computer","Critical","The powertrain control module detected an internal processor fault.",["No-start","Stalling","Multiple warning lights","Erratic operation"],["Low or unstable voltage","Poor grounds","Water intrusion","Internal module failure","Software issue"],["Check battery and charging voltage","Inspect module powers and grounds","Check for water damage","Verify software updates before replacement"],"Avoid normal driving until power and ground problems are ruled out."),
  c("P0700","Transmission Control System Malfunction","Transmission control","High","The engine computer was told that the transmission controller stored one or more faults.",["Check Engine Light","Harsh or delayed shifts","Limp mode","Transmission warning"],["A separate transmission code is stored","Electrical fault","Solenoid or sensor issue","Internal transmission problem"],["Scan the transmission control module for its specific codes","Check fluid level and condition if serviceable","Inspect power and grounds"],"Drive cautiously and avoid towing or heavy loads until the underlying code is known.",["What transmission-specific codes were retrieved?","Was fluid condition checked?","What testing supports the recommended repair?"]),
  c("P0715","Input/Turbine Speed Sensor A Circuit Malfunction","Transmission control","High","The transmission controller is not receiving a reliable input-shaft speed signal.",["Harsh shifting","Limp mode","Delayed shifts"],["Faulty speed sensor","Wiring issue","Connector contamination","Internal transmission problem"],["Compare input and output speed data","Inspect wiring and connector","Check sensor signal"],"Limit driving because shifting may be unpredictable."),
  c("P0720","Output Speed Sensor Circuit Malfunction","Transmission control","High","The transmission controller is not receiving a reliable output-speed signal.",["Incorrect speedometer","Harsh shifting","Limp mode","Cruise-control issues"],["Faulty output-speed sensor","Wiring or connector fault","Tone-wheel problem"],["Review live speed data","Inspect wiring","Test the sensor signal","Check related ABS codes"],"Use caution because shifting and speed information may be affected."),
  c("P0740","Torque Converter Clutch Circuit Malfunction","Transmission control","High","The torque-converter clutch control circuit is not operating as expected.",["Higher engine RPM at cruise","Poor fuel economy","Transmission overheating","Harsh shifting"],["TCC solenoid fault","Wiring problem","Valve-body issue","Low or contaminated fluid","Internal converter problem"],["Check transmission fluid if serviceable","Inspect wiring","Command the TCC with a scan tool","Compare commanded and actual slip"],"Avoid towing and heavy loads until diagnosed."),
  c("P0741","Torque Converter Clutch Performance or Stuck Off","Transmission control","High","The torque-converter clutch is not applying or holding as expected.",["Higher RPM at highway speed","Poor fuel economy","Transmission heat","Possible shudder"],["Worn torque converter clutch","Valve-body or solenoid problem","Fluid issue","Hydraulic leak"],["Check fluid condition","Review TCC slip data","Command clutch operation","Check for related pressure codes"],"Avoid towing and extended highway driving if the transmission is overheating.")
];

export const obdCodeMap = new Map(obdCodes.map((item) => [item.code, item]));
export const normalizeObdCode = (value: string) => value.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 5);
export const findObdCode = (value: string) => obdCodeMap.get(normalizeObdCode(value));
